import type { Metadata } from "next";
import { useTranslations } from "next-intl";
import Providers from "@/providers";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DashboardLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const t = useTranslations();

  return (
    <html lang="en">
      <body>
        <span>{t("App.Private.Dashboard.Layout")}</span>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default DashboardLayout;
