import { JSX } from "react";
import type { Metadata } from "next";
import { useTranslations } from "next-intl";
import Providers from "@/providers";
import "@/styles/globals.css";
import { TLayoutProps } from "./types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }: TLayoutProps): JSX.Element => {
  const t = useTranslations();

  return (
    <html lang="en">
      <body>
        <span>{t("App.Private.Dashboard.Layout")}</span>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default Layout;
