import type { Metadata } from "next";

import Providers from "@/providers";

import "@/styles/globals.css";
import { useTranslations } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const t = useTranslations();

  return (
    <html lang="en">
      <body>
        <span>{t("App.Public.Layout")}</span>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
