import { JSX } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const Layout = ({ children }: { children: React.ReactNode }): JSX.Element => {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default Layout;
