import type { Metadata } from "next";

import ReactQueryClientProvider from "@/providers/ReactQueryClientProvider";
import NextAuthProvider from "@/providers/NextAuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body>
          <NextAuthProvider>{children}</NextAuthProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
